development:
  service:
    url:
      fit: api/gbc/ml/document/classifier/datapreparation/fit
      transform: api/gbc/ml/document/classifier/datapreparation/transform
      training: api/gbc/ml/document/classifier/training
      predict: api/gbc/ml/document/classifier/predict
    address:
      host: 127.0.0.1
      port: 7123
  directories:
    dictionary: common/nlp/resources/dic_es.txt
    lang: es
  pre_process:
    pre_process_batch_size: 50
    max_string_size: 500000
  files:
    tf: data.tfs
    tfidf: data.tfidf
    vectorizer: vectorizer.tfidf
    vectorizer_tfidf: tfidf
  decision_tree:
    dt_model: decision_tree.model
    dt_max_depth: 64
    dt_verbose: 10
