development:
  augmentation: 19
  image_processing:
    resize_width: 450
    resize_height: 600
    crop_width: 200
    crop_height: 200
  service:
    url:
      fit: api/gbc/ml/document/classifier/datapreparation/fit
      transform: api/gbc/ml/document/classifier/datapreparation/transform
      training: api/gbc/ml/document/classifier/training
      predict: api/gbc/ml/document/classifier/predict
      pdf2readable: https://opfeekaamh.execute-api.eu-central-1.amazonaws.com/dev/api/gbc/ocr/image/pdf/readable
    pre_process:
      host: 127.0.0.1
      port: 7120
  directories:
    dictionary: common/nlp/resources/dic_es.txt
    lang: es
  pre_process:
    pre_process_batch_size: 50
    max_string_size: 500000
  files:
    tf: data.tfs
    tfidf: data.tfidf
    vectorizer: vectorizer.tfidf
    vectorizer_tfidf: tfidf
    image_file_ext: jpg
    text_file_ext: txt
    source_file_ext: pdf
    gram_file_ext: gram
  threads:
    pdf2readable: 6